#!/bin/bash
N_GPUS_PER_NODE=4
CPUS_PER_NODE=16
TEMP_DIR=/tmp/
# Generation parameters
MAX_PROMPT_LENGTH=4096
MAX_RESPONSE_LENGTH=32000
MAX_VAL_ROLLOUT_LENGTH=65536
TOKENIZER_MODEL_MAX_LENGTH=$((MAX_PROMPT_LENGTH + MAX_RESPONSE_LENGTH))
BATCH_SIZE=256
MINIBATCH_SIZE=256
BATCH_SIZE_PER_GPU=1
TEMP=0.6
TOP_P=0.95
TRAIN_FILES="['path/to/train.parquet']"
TEST_FILES="['path/to/test.parquet']"
K_EVAL=4
BETA2=0.001
BETA1=1.0
SEED=42
MODEL_NAME="deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"
EXPERIMENT_NAME="deepcoder_test_run"
CONVERT_TO_V_STAR=True
LOGGERS="['console','wandb']"
VAL_BEFORE_TRAIN=True
RUN_OFFLINE=True
USE_PRECOMPUTED_VALUES=True
TOTAL_EPOCHS=4
SHUFFLE=True
NUM_CHECKPOINTS_TO_KEEP=null  # None = keep all checkpoints
SAVE_FREQ="epoch"
TEST_FREQ="epoch"
MAX_NUM_BATCHED_TOKENS=131072 # model max for deepseek 

# LR Scheduler Params
LR_SCHEDULER="cosine"
MIN_LR_RATIO=0.05
LR_WARMUP_STEPS_RATIO=0.02

# optimizer params
LR=1e-6
OPTIMIZER_TYPE="decoupled_adamw"
OPT_BETA1=0.9
OPT_BETA2=0.95
OPT_EPS=1e-10
WEIGHT_DECAY=1e-8
TENSOR_MODEL_PARALLEL_SIZE=2
SAVE_CONTENTS="['hf_model']"
python -m verl.trainer.main_oapl \
    data.run_offline=$RUN_OFFLINE \
    data.use_precomputed_values=$USE_PRECOMPUTED_VALUES \
    data.tokenizer_model_max_length=$TOKENIZER_MODEL_MAX_LENGTH \
    algorithm.beta2=$BETA2 \
    algorithm.adv_estimator=gae \
    data.seed=$SEED \
    data.shuffle=$SHUFFLE \
    data.train_files="$TRAIN_FILES" \
    data.val_files="$TEST_FILES" \
    data.train_batch_size=$BATCH_SIZE \
    data.max_prompt_length=$MAX_PROMPT_LENGTH \
    data.max_response_length=$MAX_RESPONSE_LENGTH \
    data.filter_overlong_prompts=True \
    data.truncation='right' \
    actor_rollout_ref.model.path=$MODEL_NAME \
    actor_rollout_ref.actor.optim.lr=$LR \
    actor_rollout_ref.actor.checkpoint.save_contents=$SAVE_CONTENTS \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=$TENSOR_MODEL_PARALLEL_SIZE \
    actor_rollout_ref.actor.optim.optimizer_type=$OPTIMIZER_TYPE \
    actor_rollout_ref.actor.optim.beta1=$OPT_BETA1 \
    actor_rollout_ref.actor.optim.beta2=$OPT_BETA2 \
    actor_rollout_ref.actor.optim.eps=$OPT_EPS \
    actor_rollout_ref.actor.optim.weight_decay=$WEIGHT_DECAY \
    actor_rollout_ref.actor.optim.warmup_style=$LR_SCHEDULER \
    actor_rollout_ref.actor.optim.min_lr_ratio=$MIN_LR_RATIO \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=$LR_WARMUP_STEPS_RATIO \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=$MINIBATCH_SIZE \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=$BATCH_SIZE_PER_GPU \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=$((MAX_RESPONSE_LENGTH + MAX_PROMPT_LENGTH)) \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=$BATCH_SIZE_PER_GPU \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$TENSOR_MODEL_PARALLEL_SIZE \
    actor_rollout_ref.rollout.val_kwargs.n=$K_EVAL \
    actor_rollout_ref.rollout.val_kwargs.temperature=$TEMP \
    actor_rollout_ref.rollout.val_kwargs.top_p=$TOP_P \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.do_sample=True \
    actor_rollout_ref.rollout.temperature=$TEMP \
    actor_rollout_ref.rollout.top_p=$TOP_P \
    actor_rollout_ref.rollout.response_length=$MAX_VAL_ROLLOUT_LENGTH \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=$BATCH_SIZE_PER_GPU \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.rollout.max_num_batched_tokens=$MAX_NUM_BATCHED_TOKENS \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    critic.convert_to_v_star=$CONVERT_TO_V_STAR \
    critic.beta1=$BETA1 \
    critic.model.path=$CRITIC_MODEL_NAME \
    critic.model.use_remove_padding=False \
    critic.ppo_micro_batch_size_per_gpu=$BATCH_SIZE_PER_GPU \
    trainer.logger=$LOGGERS \
    trainer.project_name='OAPL' \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.n_gpus_per_node=$N_GPUS_PER_NODE \
    trainer.nnodes=1 \
    trainer.save_freq=$SAVE_FREQ \
    trainer.test_freq=$TEST_FREQ \
    trainer.total_epochs=$TOTAL_EPOCHS \
    trainer.val_before_train=$VAL_BEFORE_TRAIN \
    trainer.resume_mode='auto' \
    ray_init.num_cpus=$CPUS_PER_NODE \
    ray_init.temp_dir=$TEMP_DIR \
    trainer.max_actor_ckpt_to_keep=$NUM_CHECKPOINTS_TO_KEEP